question_data = [
    {
        'category': 'Entertainment: Music',
        'type': 'boolean',
        'difficulty': 'easy',
        'question': 'The music group Daft Punk got their name from a negative review they recieved.',
        'correct_answer': 'True',
        'incorrect_answers': ['False'],
    },
    {
        'category': 'Entertainment: Film',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'Velma Kelly and Roxie Hart are the protagonists of which Oscar winning movie?',
        'correct_answer': 'Chicago',
        'incorrect_answers': [
            'Dreamgirls',
            'Cabaret',
            'All That Jazz',
        ],
    },
    {
        'category': 'Entertainment: Film',
        'type': 'boolean',
        'difficulty': 'easy',
        'question': 'Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.',
        'correct_answer': 'False',
        'incorrect_answers': ['True'],
    },
    {
        'category': 'Geography',
        'type': 'multiple',
        'difficulty': 'easy',
        'question': 'Which of the following former Yugoslavian states is landlocked?',
        'correct_answer': 'Serbia',
        'incorrect_answers': [
            'Bosnia and Herzegovina',
            'Montenegro',
            'Croatia',
        ],
    },
    {
        'category': 'History',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'When was &quot;The Gadget&quot;, the first nuclear device to be detonated, tested?',
        'correct_answer': 'July 16, 1945',
        'incorrect_answers': [
            'June 22, 1945',
            'August 6, 1945',
            'April 5, 1945',
        ],
    },
    {
        'category': 'Mythology',
        'type': 'boolean',
        'difficulty': 'medium',
        'question': 'According to Norse mythology, Loki is a mother.',
        'correct_answer': 'True',
        'incorrect_answers': ['False'],
    },
    {
        'category': 'Geography',
        'type': 'boolean',
        'difficulty': 'medium',
        'question': 'Antarctica is the largest desert in the world.',
        'correct_answer': 'True',
        'incorrect_answers': ['False'],
    },
    {
        'category': 'Entertainment: Film',
        'type': 'multiple',
        'difficulty': 'easy',
        'question': 'The 2016 Disney animated film &#039;Moana&#039; is based on which culture?',
        'correct_answer': 'Polynesian',
        'incorrect_answers': ['Native American', 'Japanese', 'Nordic'],
    },
    {
        'category': 'Entertainment: Japanese Anime & Manga',
        'type': 'multiple',
        'difficulty': 'medium',
        'question': 'What was studio Trigger&#039;s first original long-form animated series for television?',
        'correct_answer': 'Kill la Kill',
        'incorrect_answers': [
            'Kiznaiver',
            'Inferno Cop',
            'Gurren Lagann',
        ],
    },
    {
        'category': 'Entertainment: Books',
        'type': 'multiple',
        'difficulty': 'easy',
        'question': 'In Romance of the Three Kingdoms, who was not a member of the Peach Garden Oath?',
        'correct_answer': 'Zhao Yun',
        'incorrect_answers': ['Liu Bei', 'Guan Yu', 'Zhang Fei'],
    },
]
